name: Nomad Investor Clubs
favicon: null
layout_spectrum: 0.19120121956802905
typography_spectrum: 0.27732184738852084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.01018771599046886
  lightness: 0.5786519206594676
  saturation: 0.9504997194744647
  rhythmicContrast: 0.4078771190252155
purpose: []
